name: "My action"
decription: "Test my action"

inputs:
  message:
    decription: "Test my action"
    required: true
    default: "Hello world"

runs: 
  using: "composite"
    

  steps:
    - name: Hola mundo
      run:  echo "Hola S{{ inputs.message }}"
      shell: bash